version: '3.8'

services:
  web:
    build:
       context: ./services/web
       dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:1177 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 1177
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 8087:80
    depends_on:
      - web

volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
